name: MSLib
main: dev.lone64.mslib.MSLibModule
author: lone64

version: '@version@'
api-version: '1.20'

softdepend: [Vault, ItemsAdder]

libraries:
  - com.zaxxer:HikariCP:5.0.1
  - org.atteo.classindex:classindex:3.13
  - com.github.cryptomorin:XSeries:11.3.0
  - org.spongepowered:configurate-yaml:4.1.2
  - com.github.kevinsawicki:http-request:6.0